import { t as e } from "./rolldown-runtime.Dh6celcD.mjs";
import {
  A as t,
  I as n,
  M as r,
  N as i,
  T as a,
  b as o,
  l as s,
  s as c,
  u as l,
  v as u,
} from "./react.CV_3rBxD.mjs";
import { C as d, a as f, r as p, t as m } from "./motion.CdSRWwto.mjs";
import {
  I as h,
  M as g,
  Mt as _,
  N as v,
  Nt as y,
  Q as b,
  W as x,
  ht as S,
  i as ee,
  j as C,
  k as w,
  o as T,
  q as E,
  wt as te,
  y as D,
} from "./framer.B0qnvVVY.mjs";
import { n as O, t as k } from "./FollowEyes.DwcgK6ML.mjs";
var A,
  j,
  M,
  N,
  P,
  F,
  I,
  L,
  R,
  z,
  B,
  V,
  H,
  U = e(() => {
    (c(),
      b(),
      m(),
      a(),
      O(),
      (A = x(k)),
      (j = E(k)),
      (M = `framer-1RMtz`),
      (N = { AmqXawdYy: `framer-v-1oto7d7` }),
      (P = (e) => {
        if (typeof e != `number`) return e;
        if (Number.isFinite(e)) return Math.max(0, e) + `px`;
      }),
      (F = (e, t) => {
        if (typeof e == `number` && Number.isFinite(e)) return Math.max(0, e) + `px`;
        if (typeof e != `string` || typeof t != `number`) return;
        let n = e.split(` `);
        return n[t] || n[t - 2] || n[0];
      }),
      (I = { bounce: 0.2, delay: 0, duration: 0.4, type: `spring` }),
      (L = ({ value: e, children: t }) => {
        let n = r(f),
          a = e ?? n.transition,
          o = i(() => ({ ...n, transition: a }), [JSON.stringify(a)]);
        return s(f.Provider, { value: o, children: t });
      }),
      (R = d.create(n)),
      (z = { One: `one`, Two: `two` }),
      (B = ({
        blinking: e,
        blinkInterval: t,
        buttonColor: n,
        eyeColor: r,
        eyeCount: i,
        eyeGapPx: a,
        eyeSizePx: o,
        height: s,
        id: c,
        link: l,
        padding: u,
        pupilColor: d,
        pupilSizePx: f,
        radius: p,
        range: m,
        speed: h,
        text: g,
        textColor: _,
        width: v,
        ...y
      }) => ({
        ...y,
        AmmV7xj6g: o ?? y.AmmV7xj6g ?? 40,
        BgmIAzzRV: p ?? y.BgmIAzzRV ?? `30px`,
        DbOmokZP0: _ ?? y.DbOmokZP0 ?? `rgb(255, 255, 255)`,
        EDzxvbp5Q: u ?? y.EDzxvbp5Q ?? `6px 6px 6px 20px`,
        F9xEnRksX: z[i] ?? i ?? y.F9xEnRksX ?? `two`,
        Ftd7ea6ZK: m ?? y.Ftd7ea6ZK ?? 90,
        GmXdHB9SX: e ?? y.GmXdHB9SX ?? !1,
        h_OXotjfD: f ?? y.h_OXotjfD ?? 12,
        LWV7WvkSz: r ?? y.LWV7WvkSz ?? `rgb(255, 255, 255)`,
        n7FNYiflu: t ?? y.n7FNYiflu ?? 2e3,
        ooNLd407F: h ?? y.ooNLd407F ?? 100,
        qcTsc8aEM: g ?? y.qcTsc8aEM ?? `Get in touch`,
        qNjswW_Tg: l ?? y.qNjswW_Tg,
        s8XHH4TvL: a ?? y.s8XHH4TvL ?? 4,
        ucHarSLTi: n ?? y.ucHarSLTi ?? `rgb(0, 0, 0)`,
        Z_ma24kbm: d ?? y.Z_ma24kbm ?? `rgb(0, 0, 0)`,
      })),
      (V = (e, t) => (e.layoutDependency ? t.join(`-`) + e.layoutDependency : t.join(`-`))),
      (H = y(
        u(function (e, r) {
          let i = t(null),
            a = r ?? i,
            c = o(),
            { activeLocale: u, setLocale: f } = te();
          S();
          let {
              style: m,
              className: g,
              layoutId: v,
              variant: y,
              qNjswW_Tg: b,
              ucHarSLTi: x,
              qcTsc8aEM: T,
              DbOmokZP0: E,
              Z_ma24kbm: O,
              LWV7WvkSz: A,
              F9xEnRksX: j,
              AmmV7xj6g: z,
              h_OXotjfD: H,
              s8XHH4TvL: U,
              ooNLd407F: W,
              Ftd7ea6ZK: G,
              GmXdHB9SX: K,
              n7FNYiflu: q,
              EDzxvbp5Q: J,
              BgmIAzzRV: Y,
              ...X
            } = B(e),
            {
              baseVariant: ne,
              classNames: Z,
              clearLoadingGesture: re,
              gestureHandlers: ie,
              gestureVariant: ae,
              isLoading: oe,
              setGestureState: se,
              setVariant: ce,
              variants: Q,
            } = _({ defaultVariant: `AmqXawdYy`, ref: a, variant: y, variantClassNames: N }),
            $ = V(e, Q),
            le = h(M);
          return s(p, {
            id: v ?? c,
            children: s(R, {
              animate: Q,
              initial: !1,
              children: s(L, {
                value: I,
                children: s(D, {
                  href: b,
                  motionChild: !0,
                  nodeId: `AmqXawdYy`,
                  openInNewTab: !1,
                  scopeId: `TLMK37qFm`,
                  children: l(d.a, {
                    ...X,
                    ...ie,
                    className: `${h(le, `framer-1oto7d7`, g, Z)} framer-13l8g7p`,
                    "data-framer-name": `Variant 1`,
                    layoutDependency: $,
                    layoutId: `AmqXawdYy`,
                    ref: a,
                    style: {
                      "--eetrnf": P(J),
                      backgroundColor: x,
                      borderBottomLeftRadius: F(Y, 3),
                      borderBottomRightRadius: F(Y, 2),
                      borderTopLeftRadius: F(Y, 0),
                      borderTopRightRadius: F(Y, 1),
                      boxShadow: `0.39809593676181976px 0.39809593676181976px 0.5629926728941875px -0.3125px rgba(0, 0, 0, 0.07), 1.207253071552259px 1.207253071552259px 1.7073136670057811px -0.625px rgba(0, 0, 0, 0.08), 3.1913267607422307px 3.1913267607422307px 4.51321758700586px -0.9375px rgba(0, 0, 0, 0.1), 10px 10px 14.142135623730951px -1.25px rgba(0, 0, 0, 0.19)`,
                      ...m,
                    },
                    children: [
                      s(w, {
                        __fromCanvasComponent: !0,
                        children: s(n, {
                          children: s(d.p, {
                            dir: `auto`,
                            style: {
                              "--font-selector": `RlM7TWFucm9wZS1ib2xk`,
                              "--framer-font-family": `"Manrope", "Manrope Placeholder", sans-serif`,
                              "--framer-font-weight": `700`,
                              "--framer-letter-spacing": `-0.02em`,
                              "--framer-line-height": `1.4em`,
                              "--framer-text-color": `var(--extracted-r6o4lv, var(--variable-reference-DbOmokZP0-TLMK37qFm))`,
                            },
                            children: `Get in touch`,
                          }),
                        }),
                        className: `framer-1k85wgo`,
                        "data-framer-name": `Text`,
                        fonts: [`FS;Manrope-bold`],
                        layoutDependency: $,
                        layoutId: `URychcbuQ`,
                        style: {
                          "--extracted-r6o4lv": `var(--variable-reference-DbOmokZP0-TLMK37qFm)`,
                          "--framer-link-text-color": `rgb(0, 153, 255)`,
                          "--framer-link-text-decoration": `underline`,
                          "--variable-reference-DbOmokZP0-TLMK37qFm": E,
                        },
                        text: T,
                        verticalAlignment: `top`,
                        withExternalLayout: !0,
                      }),
                      s(ee, {
                        children: s(C, {
                          className: `framer-1kvpqiy-container`,
                          "data-code-component-plugin-id": `84d4c1`,
                          isAuthoredByUser: !0,
                          isModuleExternal: !0,
                          layoutDependency: $,
                          layoutId: `PWzIa7T_j-container`,
                          nodeId: `PWzIa7T_j`,
                          rendersWithMotion: !0,
                          scopeId: `TLMK37qFm`,
                          children: s(k, {
                            blinkInterval: q,
                            enableBlinking: K,
                            eyeColor: A,
                            eyeCount: j,
                            eyeSize: z,
                            eyeSpacing: U,
                            height: `100%`,
                            id: `PWzIa7T_j`,
                            layoutId: `PWzIa7T_j`,
                            pupilColor: O,
                            pupilSize: H,
                            style: { height: `100%`, width: `100%` },
                            trackingRange: G,
                            trackingSpeed: W,
                            width: `100%`,
                          }),
                        }),
                      }),
                    ],
                  }),
                }),
              }),
            }),
          });
        }),
        [
          `.framer-1RMtz.framer-13l8g7p, .framer-1RMtz .framer-13l8g7p { display: block; }`,
          `.framer-1RMtz.framer-1oto7d7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: var(--eetrnf); position: relative; text-decoration: none; width: min-content; }`,
          `.framer-1RMtz .framer-1k85wgo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }`,
          `.framer-1RMtz .framer-1kvpqiy-container { flex: none; height: auto; position: relative; width: auto; }`,
        ],
        `framer-1RMtz`,
      )),
      (H.displayName = `Eye Follow Button`),
      (H.defaultProps = { height: 52, width: 221 }),
      v(H, {
        qNjswW_Tg: { title: `Link`, type: T.Link },
        ucHarSLTi: { defaultValue: `rgb(0, 0, 0)`, title: `Button Color`, type: T.Color },
        qcTsc8aEM: {
          defaultValue: `Get in touch`,
          displayTextArea: !1,
          title: `Text`,
          type: T.String,
        },
        onqcTsc8aEMChange: { changes: `qcTsc8aEM`, type: T.ChangeHandler },
        DbOmokZP0: { defaultValue: `rgb(255, 255, 255)`, title: `Text Color`, type: T.Color },
        Z_ma24kbm: { defaultValue: `rgb(0, 0, 0)`, title: `Pupil Color`, type: T.Color },
        LWV7WvkSz: { defaultValue: `rgb(255, 255, 255)`, title: `Eye Color`, type: T.Color },
        F9xEnRksX: j?.eyeCount && {
          ...j.eyeCount,
          defaultValue: `two`,
          description: void 0,
          hidden: void 0,
          optional: void 0,
          title: `Eye Count`,
        },
        onF9xEnRksXChange: { changes: `F9xEnRksX`, type: T.ChangeHandler },
        AmmV7xj6g: {
          defaultValue: 40,
          max: 300,
          min: 10,
          step: 1,
          title: `Eye Size (Px)`,
          type: T.Number,
        },
        onAmmV7xj6gChange: { changes: `AmmV7xj6g`, type: T.ChangeHandler },
        h_OXotjfD: {
          defaultValue: 12,
          max: 100,
          min: 1,
          step: 1,
          title: `Pupil Size (Px)`,
          type: T.Number,
        },
        onh_OXotjfDChange: { changes: `h_OXotjfD`, type: T.ChangeHandler },
        s8XHH4TvL: {
          defaultValue: 4,
          max: 200,
          min: 0,
          step: 1,
          title: `Eye Gap (Px)`,
          type: T.Number,
        },
        ons8XHH4TvLChange: { changes: `s8XHH4TvL`, type: T.ChangeHandler },
        ooNLd407F: {
          defaultValue: 100,
          max: 500,
          min: 50,
          step: 10,
          title: `Speed`,
          type: T.Number,
        },
        onooNLd407FChange: { changes: `ooNLd407F`, type: T.ChangeHandler },
        Ftd7ea6ZK: {
          defaultValue: 90,
          max: 100,
          min: 0,
          step: 5,
          title: `Range (%)`,
          type: T.Number,
        },
        onFtd7ea6ZKChange: { changes: `Ftd7ea6ZK`, type: T.ChangeHandler },
        GmXdHB9SX: { defaultValue: !1, title: `Blinking`, type: T.Boolean },
        onGmXdHB9SXChange: { changes: `GmXdHB9SX`, type: T.ChangeHandler },
        n7FNYiflu: {
          defaultValue: 2e3,
          max: 1e4,
          min: 500,
          step: 100,
          title: `Blink Interval`,
          type: T.Number,
        },
        onn7FNYifluChange: { changes: `n7FNYiflu`, type: T.ChangeHandler },
        EDzxvbp5Q: { defaultValue: `6px 6px 6px 20px`, title: `Padding`, type: T.Padding },
        BgmIAzzRV: { defaultValue: `30px`, title: `Radius`, type: T.BorderRadius },
      }),
      g(
        H,
        [
          {
            explicitInter: !0,
            fonts: [
              {
                cssFamilyName: `Manrope`,
                source: `fontshare`,
                style: `normal`,
                uiFamilyName: `Manrope`,
                url: `https://framerusercontent.com/third-party-assets/fontshare/wf/NGBUP45ES3F7RD5XGKPEDJ6QEPO4TMOK/EXDVWJ2EDDVVV65UENMX33EDDYBX6OF7/6P4FPMFQH7CCC7RZ4UU4NKSGJ2RLF7V5.woff2`,
                weight: `700`,
              },
            ],
          },
          ...A,
        ],
        { supportsExplicitInterCodegen: !0 },
      ));
  });
export { U as n, H as t };
//# sourceMappingURL=TLMK37qFm.CXt1_IWs.mjs.map
